// pages/_app.js acts as a global wrapper to every page generated by Next.js
// See https://nextjs.org/docs/advanced-features/custom-app

import { SessionProvider } from 'next-auth/react';
import NextNProgress from 'nextjs-progressbar';
import '@styles/globals.css';

export default function ProjectLumiere({
  Component,
  pageProps: { session, ...pageProps },
}) {
  const getLayout = Component.getLayout || ((page) => page);

  return (
    <SessionProvider session={session}>
      <NextNProgress
        color='#3e73ea'
        height={2}
        options={{ showSpinner: false }}
      />
      {getLayout(<Component {...pageProps} />)}
    </SessionProvider>
  );
}
